name: css_animation
version: 0.1.3
description: Simplified access to the CSS3 animation features
author: Dan Parnham <dan@teadriven.me.uk>
homepage: http://github.com/parnham/css_animation.dart

dependencies:
  browser: any
