name: css_animation
version: 0.1.1
description: Simplified access to the CSS3 animation features
author: Dan Parnham
homepage: http://github.com/parnham/css_animation.dart

dependencies:
  browser: any
